Integrator, notebooks and helper functions
tweag/monad-bayes pull request #149
Opened 2022-06-17 20:19 UTC by reubenharry

A variety of updates, see changelog. Most prominent are:

- a new MonadSample instance called `Integrator` along with docs and tests for it
- notebooks which work. Using nix flakes from @idontgetoutmuch to run
- many more tests, e.g. that sampler gets right mean and variance
- use of foldl package to compute sample statistics
- a variety of models from the models folder fixed up and prettified. Some rewritten with pipes
- new Bayesian data type added to Control.Monad.Bayes.Class
- readme updated

2022-06-17 20:27 UTC, reubenharry commented
@idontgetoutmuch Do you know if the CI built failure seen above is a nix thing? It looks like a nix thing, and since I copied over your nix-flake (so I could work with the notebooks) I suspect that might have done something. Thoughts? 

Other than that, this is ready to review.

2022-07-02 13:25 UTC, idontgetoutmuch requested changes
LGTM apart from CI no longer works.

2022-07-08 15:39 UTC, reubenharry commented
@idontgetoutmuch Any luck working out what the flake issue was here?

2022-07-11 16:23 UTC, idontgetoutmuch approved these changes

2022-07-11 16:36 UTC, merged